conda-forge/aws-crt-cpp-feedstock

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_common062.yaml
- .ci_support/migrations/aws_c_io0102.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Manually build aws_c_io0102

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_common064.yaml
- .ci_support/migrations/aws_c_io0106.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Manual migrations

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_common074.yaml
- .ci_support/migrations/aws_c_event_stream0212.yaml
- .ci_support/migrations/aws_c_io0112.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Migrate aws_c_event_stream0212

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_common085.yaml
- .ci_support/migrations/aws_c_io0137.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
> Rebuild for aws_c_io0137 and aws_c_common085

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_http0627.yaml
- .ci_support/migrations/aws_c_io0139.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Rebuild for aws_c_io0193

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_s3023.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Migrate aws_c_auth0622

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_cal0527.yaml
- .ci_support/migrations/aws_c_common0820.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Rebuild for aws_c_common0820-aws_c_cal0527

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_io01324.yaml
- .ci_support/migrations/aws_c_mqtt0813.yaml
- .ci_support/migrations/aws_checksums0116.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
> Some migrations

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_common0823.yaml
- .ci_support/migrations/aws_c_sdkutils0111.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Rebuild for aws_common0823

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_auth073.yaml
- .ci_support/migrations/aws_c_cal061.yaml
- .ci_support/migrations/aws_c_common_090.yaml
- .ci_support/migrations/aws_c_io01331.yaml
- .ci_support/migrations/aws_c_s30314.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Manual migrations around aws_c_common090

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_cal065.yaml
- .ci_support/migrations/aws_c_io01335.yaml
- .ci_support/migrations/aws_c_s30318.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Rebuild for aws_c_cal065 and aws_c_io01335

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_common0912.yaml
- .ci_support/migrations/aws_c_io0140.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .gitignore
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- recipe/meta.yaml
> Rebuild for aws_c_io0140 and aws_c_common0912

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_common0914.yaml
- .ci_support/migrations/aws_c_mqtt0103.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Rebuild for aws_c_mqtt0103 and aws_c_common0914

- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_common0917.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Migrate for aws_c_common0917

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_auth0722.yaml
- .ci_support/migrations/aws_c_cal0613.yaml
- .ci_support/migrations/aws_c_common0918.yaml
- .ci_support/migrations/aws_c_s3059.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Rebuild for aws_c_common0918

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_http084.yaml
- .ci_support/migrations/aws_c_io01412.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Rebuild for aws_c_io01412 and aws_c_http084

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_auth0730.yaml
- .ci_support/migrations/aws_c_http089.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Migrations 20240916

- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_common0929.yaml
- .ci_support/migrations/aws_c_io01419.yaml
- .ci_support/migrations/aws_c_mqtt0107.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- azure-pipelines.yml
- recipe/meta.yaml
> Rebuild for aws_c_common0929

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_s3067.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Rebuild for aws_c_s3067

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_common0103.yaml
- .ci_support/migrations/aws_c_http091.yaml
- .ci_support/migrations/aws_c_io0152.yaml
- .ci_support/migrations/aws_c_s3071.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Rebuild for outstanding migrations

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_http092.yaml
- .ci_support/migrations/aws_c_io0153.yaml
- .ci_support/migrations/aws_c_s3075.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Rebuild for aws_c_io0153

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/migrations/aws_c_common0121.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/recipe.yaml
> Rebuild for aws-c-common 0.12.1
